<h1>Preprocessing with data missing value</h1>

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

#load data
data = pd.read_csv('./data/melb_data.csv')
data.dtypes

Unnamed: 0         int64
Suburb            object
Address           object
Rooms              int64
Type              object
Price            float64
Method            object
SellerG           object
Date              object
Distance         float64
Postcode         float64
Bedroom2         float64
Bathroom         float64
Car              float64
Landsize         float64
BuildingArea     float64
YearBuilt        float64
CouncilArea       object
Lattitude        float64
Longtitude       float64
Regionname        object
Propertycount    float64
dtype: object

In [2]:
#Select target
y = data.Price

#To keep things simple, we 'll use only numerical predictors
melb_predictors = data.drop(["Price", "Unnamed: 0"], axis = 1)
X = melb_predictors.select_dtypes(exclude="object")

In [3]:
X.dtypes

Rooms              int64
Distance         float64
Postcode         float64
Bedroom2         float64
Bathroom         float64
Car              float64
Landsize         float64
BuildingArea     float64
YearBuilt        float64
Lattitude        float64
Longtitude       float64
Propertycount    float64
dtype: object

In [4]:
X.head(15)

,Rooms,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
0,2,2.5,3067.0,2.0,1.0,1.0,202.0,NaN,NaN,-37.7996,144.9984,4019.0
1,2,2.5,3067.0,2.0,1.0,0.0,156.0,79.0,1900.0,-37.8079,144.9934,4019.0
2,3,2.5,3067.0,3.0,2.0,0.0,134.0,150.0,1900.0,-37.8093,144.9944,4019.0
3,3,2.5,3067.0,3.0,2.0,1.0,94.0,NaN,NaN,-37.7969,144.9969,4019.0
4,4,2.5,3067.0,3.0,1.0,2.0,120.0,142.0,2014.0,-37.8072,144.9941,4019.0
5,2,2.5,3067.0,2.0,1.0,0.0,181.0,NaN,NaN,-37.8041,144.9953,4019.0
6,3,2.5,3067.0,4.0,2.0,0.0,245.0,210.0,1910.0,-37.8024,144.9993,4019.0
7,2,2.5,3067.0,2.0,1.0,2.0,256.0,107.0,1890.0,-37.8060,144.9954,4019.0
8,3,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4019.0
9,2,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4019.0
10,1,2.5,3067.0,1.0,1.0,1.0,0.0,NaN,NaN,-37.8008,144.9973,4019.0
11,2,2.5,3067.0,3.0,1.0,2.0,220.0,75.0,1900.0,-37.8010,144.9989,4019.0
12,2,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4019.0
13,2,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4019.0
14,1,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4019.0

In [11]:
X.describe()

,Rooms,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,18396.000000,18395.000000,18395.000000,14927.000000,14925.000000,14820.000000,13603.000000,7762.000000,8958.000000,15064.000000,15064.000000,18395.000000
mean,2.935040,10.389986,3107.140147,2.913043,1.538492,1.615520,558.116371,151.220219,1965.879996,-37.809849,144.996338,7517.975265
std,0.958202,6.009050,95.000995,0.964641,0.689311,0.955916,3987.326586,519.188596,37.013261,0.081152,0.106375,4488.416599
min,1.000000,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,2.000000,6.300000,3046.000000,2.000000,1.000000,1.000000,176.500000,93.000000,1950.000000,-37.858100,144.931193,4294.000000
50%,3.000000,9.700000,3085.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.803625,145.000920,6567.000000
75%,3.000000,13.300000,3149.000000,3.000000,2.000000,2.000000,651.000000,174.000000,2000.000000,-37.756270,145.060000,10331.000000
max,12.000000,48.100000,3978.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

In [9]:
print("Number of features:",len(X.columns))
print("Number of instance:",len(X.index))
X.shape

Number of features: 12
Number of instance: 18396

(18396, 12)

In [7]:
X.isnull().sum()

Rooms                0
Distance             1
Postcode             1
Bedroom2          3469
Bathroom          3471
Car               3576
Landsize          4793
BuildingArea     10634
YearBuilt         9438
Lattitude         3332
Longtitude        3332
Propertycount        1
dtype: int64

<h2>1. Try Drop all columns and rows  with missing value (NaN)</h2>

In [8]:
#Drop cols
reduced_col_X = X.dropna(axis=1, inplace=False)
print(reduced_col_X.head(10))
reduced_col_X.shape

   Rooms
0      2
1      2
2      3
3      3
4      4
5      2
6      3
7      2
8      3
9      2

(18396, 1)

In [9]:
#Drop rows
reduced_row_X = X.dropna(axis=0, inplace=False)
print(reduced_row_X.head(6))
reduced_row_X.shape

    Rooms  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  \
1       2       2.5    3067.0       2.0       1.0  0.0     156.0
2       3       2.5    3067.0       3.0       2.0  0.0     134.0
4       4       2.5    3067.0       3.0       1.0  2.0     120.0
6       3       2.5    3067.0       4.0       2.0  0.0     245.0
7       2       2.5    3067.0       2.0       1.0  2.0     256.0
11      2       2.5    3067.0       3.0       1.0  2.0     220.0

    BuildingArea  YearBuilt  Lattitude  Longtitude  Propertycount
1           79.0     1900.0   -37.8079    144.9934         4019.0
2          150.0     1900.0   -37.8093    144.9944         4019.0
4          142.0     2014.0   -37.8072    144.9941         4019.0
6          210.0     1910.0   -37.8024    144.9993         4019.0
7          107.0     1890.0   -37.8060    144.9954         4019.0
11          75.0     1900.0   -37.8010    144.9989         4019.0

(6830, 12)

<h2>2. Inputation</h2>
<p>Replace missing value with the mean value along each column</p>

In [10]:
from sklearn.impute import SimpleImputer

#Inputation
my_imputed = SimpleImputer(strategy = "mean")
imputed_X = pd.DataFrame(my_imputed.fit_transform(X))

#Imputation remove column names; put them back
imputed_X.columns = X.columns

In [11]:
imputed_X.head(10)

,Rooms,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
0,2.0,2.5,3067.0,2.000000,1.000000,1.00000,202.000000,151.220219,1965.879996,-37.799600,144.998400,4019.0
1,2.0,2.5,3067.0,2.000000,1.000000,0.00000,156.000000,79.000000,1900.000000,-37.807900,144.993400,4019.0
2,3.0,2.5,3067.0,3.000000,2.000000,0.00000,134.000000,150.000000,1900.000000,-37.809300,144.994400,4019.0
3,3.0,2.5,3067.0,3.000000,2.000000,1.00000,94.000000,151.220219,1965.879996,-37.796900,144.996900,4019.0
4,4.0,2.5,3067.0,3.000000,1.000000,2.00000,120.000000,142.000000,2014.000000,-37.807200,144.994100,4019.0
5,2.0,2.5,3067.0,2.000000,1.000000,0.00000,181.000000,151.220219,1965.879996,-37.804100,144.995300,4019.0
6,3.0,2.5,3067.0,4.000000,2.000000,0.00000,245.000000,210.000000,1910.000000,-37.802400,144.999300,4019.0
7,2.0,2.5,3067.0,2.000000,1.000000,2.00000,256.000000,107.000000,1890.000000,-37.806000,144.995400,4019.0
8,3.0,2.5,3067.0,2.913043,1.538492,1.61552,558.116371,151.220219,1965.879996,-37.809849,144.996338,4019.0
9,2.0,2.5,3067.0,2.913043,1.538492,1.61552,558.116371,151.220219,1965.879996,-37.809849,144.996338,4019.0

<h2>3. Interpolate</h2>

In [12]:
interpolated_X = X.interpolate(method="linear", limit_direction= "forward")
interpolated_X.isnull().sum()

Rooms            0
Distance         0
Postcode         0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     1
YearBuilt        1
Lattitude        0
Longtitude       0
Propertycount    0
dtype: int64

In [13]:
interpolated_X = X.interpolate(method="linear", limit_direction= "backward")
interpolated_X.isnull().sum()

Rooms            0
Distance         0
Postcode         0
Bedroom2         0
Bathroom         0
Car              0
Landsize         1
BuildingArea     0
YearBuilt        0
Lattitude        0
Longtitude       0
Propertycount    0
dtype: int64

In [14]:
X.tail(5)

,Rooms,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
18391,2,6.8,3016.0,2.0,2.0,1.0,NaN,89.0,2010.0,-37.86393,144.90484,6380.0
18392,4,6.8,3016.0,4.0,1.0,5.0,866.0,157.0,1920.0,-37.85908,144.89299,6380.0
18393,4,12.7,3085.0,4.0,3.0,2.0,NaN,NaN,NaN,-37.72006,145.10547,1369.0
18394,4,6.3,3013.0,4.0,1.0,1.0,362.0,112.0,1920.0,-37.81188,144.88449,6543.0
18395,4,6.3,3013.0,4.0,2.0,2.0,NaN,139.0,1950.0,-37.81829,144.87404,6543.0

In [15]:
interpolated_X = X.interpolate(method="linear", limit_direction= "both")
interpolated_X.isnull().sum()

Rooms            0
Distance         0
Postcode         0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
YearBuilt        0
Lattitude        0
Longtitude       0
Propertycount    0
dtype: int64

In [17]:
interpolated_X.head()

,Rooms,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
0,2,2.5,3067.0,2.0,1.0,1.0,202.0,79.0,1900.0,-37.7996,144.9984,4019.0
1,2,2.5,3067.0,2.0,1.0,0.0,156.0,79.0,1900.0,-37.8079,144.9934,4019.0
2,3,2.5,3067.0,3.0,2.0,0.0,134.0,150.0,1900.0,-37.8093,144.9944,4019.0
3,3,2.5,3067.0,3.0,2.0,1.0,94.0,146.0,1957.0,-37.7969,144.9969,4019.0
4,4,2.5,3067.0,3.0,1.0,2.0,120.0,142.0,2014.0,-37.8072,144.9941,4019.0

## 4. Training and evaluate model

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [22]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler

In [52]:
pl = Pipeline(steps=[
    ('standardscaler', StandardScaler()),
    ('randomforestregressor', RandomForestRegressor())
])
pl.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('randomforestregressor', RandomForestRegressor())])

In [57]:
predPrice= pl.predict(X_test)
print(predPrice[0:5])
print(list(y_test)[0:5])

[2139380.         1369644.78571429 1030260.27777778  805354.28571429
  938140.        ]
[1475000.0, 1901000.0, 955000.0, 1010000.0, 810000.0]

In [64]:
from sklearn.metrics import mean_absolute_error, r2_score
print("Mean Absolute Error: ", mean_absolute_error(y_test, predPrice))
print("Avaluate: ", r2_score(y_test, predPrice))

Mean Absolute Error:  184921.3516694661
Avaluate:  0.7665598213723507